/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CategoryId = bigint;
export interface Comment {
  'id' : CommentId,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export type ExternalBlob = Uint8Array;
export interface ForumCategory {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
}
export interface ForumThread {
  'id' : ThreadId,
  'categoryId' : CategoryId,
  'title' : string,
  'body' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface Listing {
  'id' : ListingId,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'isSold' : boolean,
  'timestamp' : bigint,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ListingId = bigint;
export type ReplyId = bigint;
export type ThreadId = bigint;
export interface ThreadReply {
  'id' : ReplyId,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'threadId' : ThreadId,
}
export interface ThreadWithReplies {
  'thread' : ForumThread,
  'replies' : Array<ThreadReply>,
}
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'profilePicBlob' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'principal' : Principal,
  'role' : UserRole,
  'profile' : UserProfile,
}
export interface Video {
  'id' : VideoId,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'videoBlob' : ExternalBlob,
  'likes' : bigint,
  'thumbnailBlob' : ExternalBlob,
  'timestamp' : bigint,
}
export type VideoId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[VideoId, string], CommentId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], CategoryId>,
  'createListing' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    ListingId
  >,
  'createThread' : ActorMethod<[CategoryId, string, string], ThreadId>,
  'createVideo' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob],
    VideoId
  >,
  'getAllActiveListings' : ActorMethod<[], Array<Listing>>,
  'getAllCategories' : ActorMethod<[], Array<ForumCategory>>,
  'getAllUsers' : ActorMethod<[], Array<UserWithRole>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForVideo' : ActorMethod<[VideoId], Array<Comment>>,
  'getListing' : ActorMethod<[ListingId], [] | [Listing]>,
  'getThreadWithReplies' : ActorMethod<[ThreadId], [] | [ThreadWithReplies]>,
  'getThreadsInCategory' : ActorMethod<[CategoryId], Array<ForumThread>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'markAsSold' : ActorMethod<[ListingId], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'replyToThread' : ActorMethod<[ThreadId, string], ReplyId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];