/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Nat;
export const CommentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ListingId = IDL.Nat;
export const ThreadId = IDL.Nat;
export const Listing = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'isSold' : IDL.Bool,
  'timestamp' : IDL.Int,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const ForumCategory = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'likes' : IDL.Nat,
  'thumbnailBlob' : ExternalBlob,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'videoId' : VideoId,
});
export const ForumThread = IDL.Record({
  'id' : ThreadId,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ReplyId = IDL.Nat;
export const ThreadReply = IDL.Record({
  'id' : ReplyId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'threadId' : ThreadId,
});
export const ThreadWithReplies = IDL.Record({
  'thread' : ForumThread,
  'replies' : IDL.Vec(ThreadReply),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [ListingId],
      [],
    ),
  'createThread' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [ThreadId], []),
  'createVideo' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
      [VideoId],
      [],
    ),
  'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(ForumCategory)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForVideo' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getThreadWithReplies' : IDL.Func(
      [ThreadId],
      [IDL.Opt(ThreadWithReplies)],
      ['query'],
    ),
  'getThreadsInCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(ForumThread)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'markAsSold' : IDL.Func([ListingId], [], []),
  'replyToThread' : IDL.Func([ThreadId, IDL.Text], [ReplyId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Nat;
  const CommentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ListingId = IDL.Nat;
  const ThreadId = IDL.Nat;
  const Listing = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'isSold' : IDL.Bool,
    'timestamp' : IDL.Int,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const ForumCategory = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'likes' : IDL.Nat,
    'thumbnailBlob' : ExternalBlob,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'videoId' : VideoId,
  });
  const ForumThread = IDL.Record({
    'id' : ThreadId,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ReplyId = IDL.Nat;
  const ThreadReply = IDL.Record({
    'id' : ReplyId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'threadId' : ThreadId,
  });
  const ThreadWithReplies = IDL.Record({
    'thread' : ForumThread,
    'replies' : IDL.Vec(ThreadReply),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [ListingId],
        [],
      ),
    'createThread' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [ThreadId], []),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
        [VideoId],
        [],
      ),
    'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(ForumCategory)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForVideo' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getThreadWithReplies' : IDL.Func(
        [ThreadId],
        [IDL.Opt(ThreadWithReplies)],
        ['query'],
      ),
    'getThreadsInCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(ForumThread)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'markAsSold' : IDL.Func([ListingId], [], []),
    'replyToThread' : IDL.Func([ThreadId, IDL.Text], [ReplyId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };