/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CategoryId = bigint;
export type ChannelId = bigint;
export interface Comment {
  'id' : CommentId,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export interface DownloadRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'requester' : Principal,
  'shopId' : ShopId,
  'productId' : ShopProductId,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface ForumCategory {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
}
export interface ForumThread {
  'id' : ThreadId,
  'categoryId' : CategoryId,
  'title' : string,
  'body' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface Group {
  'id' : GroupId,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'isNsfw' : boolean,
  'iconBlob' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'category' : string,
}
export interface GroupChannel {
  'id' : ChannelId,
  'name' : string,
  'description' : string,
  'groupId' : GroupId,
}
export type GroupId = bigint;
export interface GroupMessage {
  'id' : GroupMessageId,
  'channelId' : ChannelId,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type GroupMessageId = bigint;
export interface Listing {
  'id' : ListingId,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'isSold' : boolean,
  'timestamp' : bigint,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ListingId = bigint;
export interface PurchaseRecord {
  'id' : bigint,
  'shopId' : ShopId,
  'productTitle' : string,
  'productId' : ShopProductId,
  'currency' : string,
  'timestamp' : bigint,
  'buyer' : Principal,
  'price' : bigint,
}
export type ReplyId = bigint;
export interface SellerAlert {
  'id' : bigint,
  'alertType' : { 'downloadRequest' : null } |
    { 'purchase' : null },
  'shopId' : ShopId,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'buyerPrincipal' : Principal,
  'relatedId' : bigint,
}
export interface Shop {
  'id' : ShopId,
  'categories' : Array<string>,
  'contactInfo' : string,
  'bannerBlob' : [] | [ExternalBlob],
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'isNsfw' : boolean,
  'logoBlob' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'rules' : string,
}
export interface ShopCategory {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
}
export type ShopId = bigint;
export interface ShopProduct {
  'id' : ShopProductId,
  'title' : string,
  'shopId' : ShopId,
  'description' : string,
  'stock' : bigint,
  'digitalFileBlob' : [] | [ExternalBlob],
  'currency' : string,
  'timestamp' : bigint,
  'paymentLink' : string,
  'category' : string,
  'imageBlobs' : Array<ExternalBlob>,
  'price' : bigint,
  'isDigital' : boolean,
}
export type ShopProductId = bigint;
export interface ShopQuestion {
  'id' : bigint,
  'asker' : Principal,
  'shopId' : ShopId,
  'question' : string,
  'answered' : boolean,
  'answer' : string,
  'timestamp' : bigint,
}
export interface ShopReview {
  'id' : bigint,
  'shopId' : ShopId,
  'comment' : string,
  'timestamp' : bigint,
  'rating' : bigint,
  'reviewer' : Principal,
}
export interface ShoppingCartView {
  'productIds' : Array<bigint>,
  'owner' : Principal,
  'timestamp' : bigint,
}
export type ThreadId = bigint;
export interface ThreadReply {
  'id' : ReplyId,
  'text' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'threadId' : ThreadId,
}
export interface ThreadWithReplies {
  'thread' : ForumThread,
  'replies' : Array<ThreadReply>,
}
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'profilePicBlob' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'principal' : Principal,
  'isCreator' : boolean,
  'role' : UserRole,
  'profile' : UserProfile,
}
export interface Video {
  'id' : VideoId,
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'videoBlob' : ExternalBlob,
  'likes' : bigint,
  'thumbnailBlob' : ExternalBlob,
  'timestamp' : bigint,
}
export type VideoId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCartProduct' : ActorMethod<[bigint], undefined>,
  'addComment' : ActorMethod<[VideoId, string], CommentId>,
  'addShopProduct' : ActorMethod<
    [
      ShopId,
      string,
      string,
      bigint,
      string,
      Array<ExternalBlob>,
      string,
      bigint,
      boolean,
      string,
      [] | [ExternalBlob],
    ],
    ShopProductId
  >,
  'addShopReview' : ActorMethod<[ShopId, bigint, string], bigint>,
  'answerShopQuestion' : ActorMethod<[bigint, string], undefined>,
  'approveDownload' : ActorMethod<[bigint], undefined>,
  'askShopQuestion' : ActorMethod<[ShopId, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUserFromGroup' : ActorMethod<[GroupId, Principal], undefined>,
  'banUserFromShop' : ActorMethod<[ShopId, Principal], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<[string, string], CategoryId>,
  'createGroup' : ActorMethod<
    [string, string, [] | [ExternalBlob], [] | [ExternalBlob], boolean, string],
    GroupId
  >,
  'createGroupChannel' : ActorMethod<[GroupId, string, string], ChannelId>,
  'createListing' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    ListingId
  >,
  'createShop' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      boolean,
      Array<string>,
      [] | [ExternalBlob],
    ],
    ShopId
  >,
  'createShopCategory' : ActorMethod<[string], bigint>,
  'createThread' : ActorMethod<[CategoryId, string, string], ThreadId>,
  'createVideo' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob],
    VideoId
  >,
  'deleteShop' : ActorMethod<[ShopId], undefined>,
  'deleteShopCategory' : ActorMethod<[bigint], undefined>,
  'deleteShopProduct' : ActorMethod<[ShopProductId], undefined>,
  'dismissAlert' : ActorMethod<[bigint], undefined>,
  'getAllActiveListings' : ActorMethod<[], Array<Listing>>,
  'getAllCategories' : ActorMethod<[], Array<ForumCategory>>,
  'getAllGroups' : ActorMethod<[], Array<Group>>,
  'getAllShopCategories' : ActorMethod<[], Array<ShopCategory>>,
  'getAllShops' : ActorMethod<[], Array<Shop>>,
  'getAllUsers' : ActorMethod<[], Array<UserWithRole>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], [] | [ShoppingCartView]>,
  'getCommentsForVideo' : ActorMethod<[VideoId], Array<Comment>>,
  'getDatabaseCounts' : ActorMethod<
    [],
    {
      'categories' : bigint,
      'groups' : bigint,
      'shopProducts' : bigint,
      'listings' : bigint,
      'downloadRequests' : bigint,
      'threads' : bigint,
      'shopQuestions' : bigint,
      'shops' : bigint,
      'videos' : bigint,
    }
  >,
  'getDownloadRequests' : ActorMethod<[ShopId], Array<DownloadRequest>>,
  'getGroup' : ActorMethod<[GroupId], [] | [Group]>,
  'getGroupBans' : ActorMethod<[GroupId], Array<Principal>>,
  'getGroupChannels' : ActorMethod<[GroupId], Array<GroupChannel>>,
  'getGroupMembers' : ActorMethod<[GroupId], Array<Principal>>,
  'getGroupMessages' : ActorMethod<[ChannelId], Array<GroupMessage>>,
  'getListing' : ActorMethod<[ListingId], [] | [Listing]>,
  'getMyDownloadRequests' : ActorMethod<
    [],
    Array<[DownloadRequest, [] | [ShopProduct]]>
  >,
  'getMyPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getMyReviews' : ActorMethod<[], Array<ShopReview>>,
  'getMyShopReview' : ActorMethod<[ShopId], [] | [ShopReview]>,
  'getPublicUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getSellerAlerts' : ActorMethod<[ShopId], Array<SellerAlert>>,
  'getShop' : ActorMethod<[ShopId], [] | [Shop]>,
  'getShopBans' : ActorMethod<[ShopId], Array<Principal>>,
  'getShopProducts' : ActorMethod<[ShopId], Array<ShopProduct>>,
  'getShopPurchases' : ActorMethod<[ShopId], Array<PurchaseRecord>>,
  'getShopQuestions' : ActorMethod<[ShopId], Array<ShopQuestion>>,
  'getShopReviews' : ActorMethod<[ShopId], Array<ShopReview>>,
  'getShopsByOwner' : ActorMethod<[Principal], Array<Shop>>,
  'getThreadWithReplies' : ActorMethod<[ThreadId], [] | [ThreadWithReplies]>,
  'getThreadsInCategory' : ActorMethod<[CategoryId], Array<ForumThread>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerCreatorOrAdmin' : ActorMethod<[], boolean>,
  'isUserBannedFromGroup' : ActorMethod<[GroupId, Principal], boolean>,
  'isUserBannedFromShop' : ActorMethod<[ShopId, Principal], boolean>,
  'joinGroup' : ActorMethod<[GroupId], undefined>,
  'leaveGroup' : ActorMethod<[GroupId], undefined>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'markAlertRead' : ActorMethod<[bigint], undefined>,
  'markAllAlertsRead' : ActorMethod<[ShopId], undefined>,
  'markAsSold' : ActorMethod<[ListingId], undefined>,
  'postGroupMessage' : ActorMethod<[ChannelId, string], GroupMessageId>,
  'recordPurchase' : ActorMethod<[ShopProductId], bigint>,
  'registerCallerAsUser' : ActorMethod<[], undefined>,
  'rejectDownload' : ActorMethod<[bigint], undefined>,
  'removeCartProduct' : ActorMethod<[bigint], undefined>,
  'removeUser' : ActorMethod<[Principal], undefined>,
  'replyToThread' : ActorMethod<[ThreadId, string], ReplyId>,
  'requestDownload' : ActorMethod<[ShopProductId], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCreatorStatus' : ActorMethod<[Principal, boolean], undefined>,
  'unbanUserFromGroup' : ActorMethod<[GroupId, Principal], undefined>,
  'unbanUserFromShop' : ActorMethod<[ShopId, Principal], undefined>,
  'updateGroup' : ActorMethod<
    [GroupId, string, string, [] | [ExternalBlob], boolean, string],
    undefined
  >,
  'updateShop' : ActorMethod<
    [
      ShopId,
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      boolean,
      Array<string>,
    ],
    undefined
  >,
  'updateShopCategory' : ActorMethod<[bigint, string], undefined>,
  'updateShopProduct' : ActorMethod<
    [
      ShopProductId,
      string,
      string,
      bigint,
      string,
      Array<ExternalBlob>,
      string,
      bigint,
      boolean,
      string,
      [] | [ExternalBlob],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];