/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Nat;
export const CommentId = IDL.Nat;
export const ShopId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ShopProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GroupId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const ChannelId = IDL.Nat;
export const ListingId = IDL.Nat;
export const ThreadId = IDL.Nat;
export const Listing = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'isSold' : IDL.Bool,
  'timestamp' : IDL.Int,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const ForumCategory = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Group = IDL.Record({
  'id' : GroupId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isNsfw' : IDL.Bool,
  'iconBlob' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const ShopCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Shop = IDL.Record({
  'id' : ShopId,
  'categories' : IDL.Vec(IDL.Text),
  'contactInfo' : IDL.Text,
  'bannerBlob' : IDL.Opt(ExternalBlob),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isNsfw' : IDL.Bool,
  'logoBlob' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'rules' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePicBlob' : IDL.Opt(ExternalBlob),
});
export const UserWithRole = IDL.Record({
  'principal' : IDL.Principal,
  'isCreator' : IDL.Bool,
  'role' : UserRole,
  'profile' : UserProfile,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'likes' : IDL.Nat,
  'thumbnailBlob' : ExternalBlob,
  'timestamp' : IDL.Int,
});
export const ShoppingCartView = IDL.Record({
  'productIds' : IDL.Vec(IDL.Nat),
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'videoId' : VideoId,
});
export const DownloadRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'requester' : IDL.Principal,
  'shopId' : ShopId,
  'productId' : ShopProductId,
  'timestamp' : IDL.Int,
});
export const GroupChannel = IDL.Record({
  'id' : ChannelId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'groupId' : GroupId,
});
export const GroupMessageId = IDL.Nat;
export const GroupMessage = IDL.Record({
  'id' : GroupMessageId,
  'channelId' : ChannelId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ShopProduct = IDL.Record({
  'id' : ShopProductId,
  'title' : IDL.Text,
  'shopId' : ShopId,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'digitalFileBlob' : IDL.Opt(ExternalBlob),
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'paymentLink' : IDL.Text,
  'category' : IDL.Text,
  'imageBlobs' : IDL.Vec(ExternalBlob),
  'price' : IDL.Nat,
  'isDigital' : IDL.Bool,
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Nat,
  'shopId' : ShopId,
  'productTitle' : IDL.Text,
  'productId' : ShopProductId,
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'buyer' : IDL.Principal,
  'price' : IDL.Nat,
});
export const ShopReview = IDL.Record({
  'id' : IDL.Nat,
  'shopId' : ShopId,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const SellerAlert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Variant({
    'downloadRequest' : IDL.Null,
    'purchase' : IDL.Null,
  }),
  'shopId' : ShopId,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'buyerPrincipal' : IDL.Principal,
  'relatedId' : IDL.Nat,
});
export const ShopQuestion = IDL.Record({
  'id' : IDL.Nat,
  'asker' : IDL.Principal,
  'shopId' : ShopId,
  'question' : IDL.Text,
  'answered' : IDL.Bool,
  'answer' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ForumThread = IDL.Record({
  'id' : ThreadId,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ReplyId = IDL.Nat;
export const ThreadReply = IDL.Record({
  'id' : ReplyId,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'threadId' : ThreadId,
});
export const ThreadWithReplies = IDL.Record({
  'thread' : ForumThread,
  'replies' : IDL.Vec(ThreadReply),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCartProduct' : IDL.Func([IDL.Nat], [], []),
  'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
  'addShopProduct' : IDL.Func(
      [
        ShopId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [ShopProductId],
      [],
    ),
  'addShopReview' : IDL.Func([ShopId, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'answerShopQuestion' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'approveDownload' : IDL.Func([IDL.Nat], [], []),
  'askShopQuestion' : IDL.Func([ShopId, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUserFromGroup' : IDL.Func([GroupId, IDL.Principal], [], []),
  'banUserFromShop' : IDL.Func([ShopId, IDL.Principal], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'clearCart' : IDL.Func([], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
  'createGroup' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob), IDL.Bool, IDL.Text],
      [GroupId],
      [],
    ),
  'createGroupChannel' : IDL.Func(
      [GroupId, IDL.Text, IDL.Text],
      [ChannelId],
      [],
    ),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [ListingId],
      [],
    ),
  'createShop' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Vec(IDL.Text),
        IDL.Opt(ExternalBlob),
      ],
      [ShopId],
      [],
    ),
  'createShopCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createThread' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [ThreadId], []),
  'createVideo' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
      [VideoId],
      [],
    ),
  'deleteShop' : IDL.Func([ShopId], [], []),
  'deleteShopCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteShopProduct' : IDL.Func([ShopProductId], [], []),
  'dismissAlert' : IDL.Func([IDL.Nat], [], []),
  'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(ForumCategory)], ['query']),
  'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getAllShopCategories' : IDL.Func([], [IDL.Vec(ShopCategory)], ['query']),
  'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Opt(ShoppingCartView)], ['query']),
  'getCommentsForVideo' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'getDatabaseCounts' : IDL.Func(
      [],
      [
        IDL.Record({
          'categories' : IDL.Nat,
          'groups' : IDL.Nat,
          'shopProducts' : IDL.Nat,
          'listings' : IDL.Nat,
          'downloadRequests' : IDL.Nat,
          'threads' : IDL.Nat,
          'shopQuestions' : IDL.Nat,
          'shops' : IDL.Nat,
          'videos' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDownloadRequests' : IDL.Func(
      [ShopId],
      [IDL.Vec(DownloadRequest)],
      ['query'],
    ),
  'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
  'getGroupBans' : IDL.Func([GroupId], [IDL.Vec(IDL.Principal)], ['query']),
  'getGroupChannels' : IDL.Func([GroupId], [IDL.Vec(GroupChannel)], ['query']),
  'getGroupMembers' : IDL.Func([GroupId], [IDL.Vec(IDL.Principal)], ['query']),
  'getGroupMessages' : IDL.Func(
      [ChannelId],
      [IDL.Vec(GroupMessage)],
      ['query'],
    ),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getMyDownloadRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DownloadRequest, IDL.Opt(ShopProduct)))],
      ['query'],
    ),
  'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getMyReviews' : IDL.Func([], [IDL.Vec(ShopReview)], ['query']),
  'getMyShopReview' : IDL.Func([ShopId], [IDL.Opt(ShopReview)], ['query']),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getSellerAlerts' : IDL.Func([ShopId], [IDL.Vec(SellerAlert)], ['query']),
  'getShop' : IDL.Func([ShopId], [IDL.Opt(Shop)], ['query']),
  'getShopBans' : IDL.Func([ShopId], [IDL.Vec(IDL.Principal)], ['query']),
  'getShopProducts' : IDL.Func([ShopId], [IDL.Vec(ShopProduct)], ['query']),
  'getShopPurchases' : IDL.Func([ShopId], [IDL.Vec(PurchaseRecord)], ['query']),
  'getShopQuestions' : IDL.Func([ShopId], [IDL.Vec(ShopQuestion)], ['query']),
  'getShopReviews' : IDL.Func([ShopId], [IDL.Vec(ShopReview)], ['query']),
  'getShopsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Shop)], ['query']),
  'getThreadWithReplies' : IDL.Func(
      [ThreadId],
      [IDL.Opt(ThreadWithReplies)],
      ['query'],
    ),
  'getThreadsInCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(ForumThread)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerCreatorOrAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBannedFromGroup' : IDL.Func(
      [GroupId, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'isUserBannedFromShop' : IDL.Func(
      [ShopId, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'joinGroup' : IDL.Func([GroupId], [], []),
  'leaveGroup' : IDL.Func([GroupId], [], []),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'markAlertRead' : IDL.Func([IDL.Nat], [], []),
  'markAllAlertsRead' : IDL.Func([ShopId], [], []),
  'markAsSold' : IDL.Func([ListingId], [], []),
  'postGroupMessage' : IDL.Func([ChannelId, IDL.Text], [GroupMessageId], []),
  'recordPurchase' : IDL.Func([ShopProductId], [IDL.Nat], []),
  'registerCallerAsUser' : IDL.Func([], [], []),
  'rejectDownload' : IDL.Func([IDL.Nat], [], []),
  'removeCartProduct' : IDL.Func([IDL.Nat], [], []),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'replyToThread' : IDL.Func([ThreadId, IDL.Text], [ReplyId], []),
  'requestDownload' : IDL.Func([ShopProductId], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCreatorStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'unbanUserFromGroup' : IDL.Func([GroupId, IDL.Principal], [], []),
  'unbanUserFromShop' : IDL.Func([ShopId, IDL.Principal], [], []),
  'updateGroup' : IDL.Func(
      [GroupId, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'updateShop' : IDL.Func(
      [
        ShopId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Bool,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateShopCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateShopProduct' : IDL.Func(
      [
        ShopProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Nat;
  const CommentId = IDL.Nat;
  const ShopId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ShopProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GroupId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const ChannelId = IDL.Nat;
  const ListingId = IDL.Nat;
  const ThreadId = IDL.Nat;
  const Listing = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'isSold' : IDL.Bool,
    'timestamp' : IDL.Int,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const ForumCategory = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Group = IDL.Record({
    'id' : GroupId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isNsfw' : IDL.Bool,
    'iconBlob' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const ShopCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Shop = IDL.Record({
    'id' : ShopId,
    'categories' : IDL.Vec(IDL.Text),
    'contactInfo' : IDL.Text,
    'bannerBlob' : IDL.Opt(ExternalBlob),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isNsfw' : IDL.Bool,
    'logoBlob' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'rules' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePicBlob' : IDL.Opt(ExternalBlob),
  });
  const UserWithRole = IDL.Record({
    'principal' : IDL.Principal,
    'isCreator' : IDL.Bool,
    'role' : UserRole,
    'profile' : UserProfile,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'likes' : IDL.Nat,
    'thumbnailBlob' : ExternalBlob,
    'timestamp' : IDL.Int,
  });
  const ShoppingCartView = IDL.Record({
    'productIds' : IDL.Vec(IDL.Nat),
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'videoId' : VideoId,
  });
  const DownloadRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'requester' : IDL.Principal,
    'shopId' : ShopId,
    'productId' : ShopProductId,
    'timestamp' : IDL.Int,
  });
  const GroupChannel = IDL.Record({
    'id' : ChannelId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'groupId' : GroupId,
  });
  const GroupMessageId = IDL.Nat;
  const GroupMessage = IDL.Record({
    'id' : GroupMessageId,
    'channelId' : ChannelId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ShopProduct = IDL.Record({
    'id' : ShopProductId,
    'title' : IDL.Text,
    'shopId' : ShopId,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'digitalFileBlob' : IDL.Opt(ExternalBlob),
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'paymentLink' : IDL.Text,
    'category' : IDL.Text,
    'imageBlobs' : IDL.Vec(ExternalBlob),
    'price' : IDL.Nat,
    'isDigital' : IDL.Bool,
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Nat,
    'shopId' : ShopId,
    'productTitle' : IDL.Text,
    'productId' : ShopProductId,
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'buyer' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const ShopReview = IDL.Record({
    'id' : IDL.Nat,
    'shopId' : ShopId,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const SellerAlert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Variant({
      'downloadRequest' : IDL.Null,
      'purchase' : IDL.Null,
    }),
    'shopId' : ShopId,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'buyerPrincipal' : IDL.Principal,
    'relatedId' : IDL.Nat,
  });
  const ShopQuestion = IDL.Record({
    'id' : IDL.Nat,
    'asker' : IDL.Principal,
    'shopId' : ShopId,
    'question' : IDL.Text,
    'answered' : IDL.Bool,
    'answer' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ForumThread = IDL.Record({
    'id' : ThreadId,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ReplyId = IDL.Nat;
  const ThreadReply = IDL.Record({
    'id' : ReplyId,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'threadId' : ThreadId,
  });
  const ThreadWithReplies = IDL.Record({
    'thread' : ForumThread,
    'replies' : IDL.Vec(ThreadReply),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCartProduct' : IDL.Func([IDL.Nat], [], []),
    'addComment' : IDL.Func([VideoId, IDL.Text], [CommentId], []),
    'addShopProduct' : IDL.Func(
        [
          ShopId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [ShopProductId],
        [],
      ),
    'addShopReview' : IDL.Func([ShopId, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'answerShopQuestion' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'approveDownload' : IDL.Func([IDL.Nat], [], []),
    'askShopQuestion' : IDL.Func([ShopId, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUserFromGroup' : IDL.Func([GroupId, IDL.Principal], [], []),
    'banUserFromShop' : IDL.Func([ShopId, IDL.Principal], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'clearCart' : IDL.Func([], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
    'createGroup' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob), IDL.Bool, IDL.Text],
        [GroupId],
        [],
      ),
    'createGroupChannel' : IDL.Func(
        [GroupId, IDL.Text, IDL.Text],
        [ChannelId],
        [],
      ),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [ListingId],
        [],
      ),
    'createShop' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Vec(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [ShopId],
        [],
      ),
    'createShopCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createThread' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [ThreadId], []),
    'createVideo' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob],
        [VideoId],
        [],
      ),
    'deleteShop' : IDL.Func([ShopId], [], []),
    'deleteShopCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteShopProduct' : IDL.Func([ShopProductId], [], []),
    'dismissAlert' : IDL.Func([IDL.Nat], [], []),
    'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(ForumCategory)], ['query']),
    'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getAllShopCategories' : IDL.Func([], [IDL.Vec(ShopCategory)], ['query']),
    'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Opt(ShoppingCartView)], ['query']),
    'getCommentsForVideo' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'getDatabaseCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'categories' : IDL.Nat,
            'groups' : IDL.Nat,
            'shopProducts' : IDL.Nat,
            'listings' : IDL.Nat,
            'downloadRequests' : IDL.Nat,
            'threads' : IDL.Nat,
            'shopQuestions' : IDL.Nat,
            'shops' : IDL.Nat,
            'videos' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDownloadRequests' : IDL.Func(
        [ShopId],
        [IDL.Vec(DownloadRequest)],
        ['query'],
      ),
    'getGroup' : IDL.Func([GroupId], [IDL.Opt(Group)], ['query']),
    'getGroupBans' : IDL.Func([GroupId], [IDL.Vec(IDL.Principal)], ['query']),
    'getGroupChannels' : IDL.Func(
        [GroupId],
        [IDL.Vec(GroupChannel)],
        ['query'],
      ),
    'getGroupMembers' : IDL.Func(
        [GroupId],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroupMessages' : IDL.Func(
        [ChannelId],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getMyDownloadRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DownloadRequest, IDL.Opt(ShopProduct)))],
        ['query'],
      ),
    'getMyPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getMyReviews' : IDL.Func([], [IDL.Vec(ShopReview)], ['query']),
    'getMyShopReview' : IDL.Func([ShopId], [IDL.Opt(ShopReview)], ['query']),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getSellerAlerts' : IDL.Func([ShopId], [IDL.Vec(SellerAlert)], ['query']),
    'getShop' : IDL.Func([ShopId], [IDL.Opt(Shop)], ['query']),
    'getShopBans' : IDL.Func([ShopId], [IDL.Vec(IDL.Principal)], ['query']),
    'getShopProducts' : IDL.Func([ShopId], [IDL.Vec(ShopProduct)], ['query']),
    'getShopPurchases' : IDL.Func(
        [ShopId],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getShopQuestions' : IDL.Func([ShopId], [IDL.Vec(ShopQuestion)], ['query']),
    'getShopReviews' : IDL.Func([ShopId], [IDL.Vec(ShopReview)], ['query']),
    'getShopsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Shop)], ['query']),
    'getThreadWithReplies' : IDL.Func(
        [ThreadId],
        [IDL.Opt(ThreadWithReplies)],
        ['query'],
      ),
    'getThreadsInCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(ForumThread)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerCreatorOrAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBannedFromGroup' : IDL.Func(
        [GroupId, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isUserBannedFromShop' : IDL.Func(
        [ShopId, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'joinGroup' : IDL.Func([GroupId], [], []),
    'leaveGroup' : IDL.Func([GroupId], [], []),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'markAlertRead' : IDL.Func([IDL.Nat], [], []),
    'markAllAlertsRead' : IDL.Func([ShopId], [], []),
    'markAsSold' : IDL.Func([ListingId], [], []),
    'postGroupMessage' : IDL.Func([ChannelId, IDL.Text], [GroupMessageId], []),
    'recordPurchase' : IDL.Func([ShopProductId], [IDL.Nat], []),
    'registerCallerAsUser' : IDL.Func([], [], []),
    'rejectDownload' : IDL.Func([IDL.Nat], [], []),
    'removeCartProduct' : IDL.Func([IDL.Nat], [], []),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'replyToThread' : IDL.Func([ThreadId, IDL.Text], [ReplyId], []),
    'requestDownload' : IDL.Func([ShopProductId], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCreatorStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'unbanUserFromGroup' : IDL.Func([GroupId, IDL.Principal], [], []),
    'unbanUserFromShop' : IDL.Func([ShopId, IDL.Principal], [], []),
    'updateGroup' : IDL.Func(
        [
          GroupId,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateShop' : IDL.Func(
        [
          ShopId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Bool,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateShopCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateShopProduct' : IDL.Func(
        [
          ShopProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };